const tplHelloSource = document.querySelector('#template-hello').innerHTML;
const tplHello = Handlebars.compile(tplHelloSource);
const dataHello = {firstName: 'John', lastName: 'Smith'};
let generatedHTML = tplHello(dataHello);
const targetElement = document.body;
targetElement.insertAdjacentHTML('beforeend', generatedHTML);
console.log('tplHello:');
console.log(tplHelloSource);
console.log('=========');
console.log('dataHello:');
console.log(dataHello);
console.log('=========');
console.log('generatedHTML:');
console.log(generatedHTML);
console.log('=========');